version: '2'
services:
  db:
    environment: 
      - POSTGRES_PASSWORD=password
    image: postgres:10
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build: 
      context: ./
      dockerfile: server.Dockerfile
    volumes:
      - ./server:/server
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
