version: '2'
services:
  db2:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata2:/var/lib/postgresql/data
  server2:
    build: 
      context: ./
      dockerfile: server.Dockerfile
    working_dir: /server
    command: /server/run.sh
    volumes:
      - ./server:/server
    ports:
      - "8080:8080"
    depends_on:
      - db2
volumes:
  pgdata2:
