# Generated by Django 3.1.7 on 2021-10-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('steps', models.IntegerField()),
            ],
        ),
    ]
