# Generated by Django 3.1.7 on 2021-10-05 21:18

from django.db import migrations, models
import uuid


def fill_model2_id2(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Model2 = apps.get_model('data', 'Model2')
    for obj in Model2.objects.using(db_alias).all():
        obj.id2 = uuid.uuid4()
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_model2'),
    ]

    operations = [
        migrations.AddField(
            model_name='model2',
            name='id2',
            field=models.UUIDField(null=True),
        ),
        # migrations.RunPython(fill_model2_id2, migrations.RunPython.noop),
        # migrations.AlterField(
        #     model_name='model2',
        #     name='id2',
        #     field=models.UUIDField(default=uuid.uuid4, serialize=False, editable=False, unique=True),
        # ),
        # migrations.RemoveField(
        #     model_name='model2',
        #     name='id',
        # ),
        # migrations.RenameField(
        #     model_name='model2',
        #     old_name='id2',
        #     new_name='id'
        # ),
        # migrations.AlterField(
        #     model_name='mymodel',
        #     name='id',
        #     field=models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False),
        # ),
    ]
