# Generated by Django 3.1.7 on 2021-10-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_model2'),
    ]

    operations = [
        migrations.RunSQL(sql="CREATE TABLE data_model2_backup AS SELECT * FROM data_model2;", reverse_sql=migrations.RunSQL.noop),
    ]
