# Generated by Django 3.1.7 on 2021-10-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_backup_model2'),
    ]

    operations = [
        migrations.RunSQL(sql="ALTER TABLE data_model2 RENAME TO data_model2_temp;", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="DELETE FROM data_model2_temp;", reverse_sql=migrations.RunSQL.noop),
    ]
