# Generated by Django 3.1.7 on 2021-10-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_model2_id2'),
    ]

    operations = [
        migrations.AddField(
            model_name='model2',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
