# Generated by Django 3.1.7 on 2021-10-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_model2_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='uuid',
        ),
    ]
