# Generated by Django 3.1.7 on 2021-10-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20211006_0658'),
    ]

    operations = [
        migrations.RunSQL(sql="CREATE TABLE data_model1_backup AS SELECT * FROM data_model1;", reverse_sql=migrations.RunSQL.noop),
    ]
