# Generated by Django 3.1.7 on 2021-10-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_model2_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='model2',
            name='id2',
            field=models.UUIDField(null=True),
        ),
    ]
