# Generated by Django 3.1.7 on 2021-10-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_backup_model1'),
    ]

    operations = [
        migrations.RunSQL(sql="ALTER TABLE data_model1 RENAME TO data_model1_temp;", reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(sql="DELETE FROM data_model1_temp;", reverse_sql=migrations.RunSQL.noop),
    ]
