# Generated by Django 3.1.7 on 2021-10-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_delete_model1'),
    ]

    operations = [
        migrations.RunSQL(sql="CREATE TABLE data_model1 AS SELECT gen_random_uuid() as id, time, user_id, steps from data_model1_backup;", reverse_sql=migrations.RunSQL.noop),
    ]
