# Generated by Django 3.1.7 on 2021-10-06 00:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_update_id2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model2',
            name='id2',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, unique=True),
        ),
    ]
