# Generated by Django 3.1.7 on 2021-10-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_id2'),
    ]

    operations = [
        migrations.RemoveField('model2', 'id')
    ]
