# Generated by Django 3.1.7 on 2021-10-06 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_convert_model1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
