# Generated by Django 3.1.7 on 2021-10-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_id'),
    ]

    operations = [
        migrations.RenameField(model_name='model2', old_name='id2', new_name='id'),
    ]
